### ISSUE TITLE
Suggested improvements for TESTed-DSL

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#122]
First of all, this is how I would name it: TESTed-DSL.

I also have some suggestions for name changes:

- rename `'testcases` into `runs` (or `executions`): the testcases in a `run` could be further grouped into `context`s (#115)
- rename `'tests` into `testcases`: a run contains several testcases
- rename `'link_files` into `files`: the files could serve other purposes than just linking
- rename `'content` into `url`

This is how it looks now:

```yaml
- tab: "Inspect"
  testcases:
  - tests:
    - statement: 'inspect("code01.txt")'
      return: 5
    link_files:
    - name: "code01.txt"
      content: "media/workdir/code01.txt"
  - tests:
    - statement: 'inspect("code02.txt")'
      return: 1939
    link_files:
    - name: "code02.txt"
      content: "media/workdir/code02.txt"
```

This is how it would look with the suggestions:

```yaml
- tab: "Inspect"
  runs:
  - testcases:
    - statement: 'inspect("code01.txt")'
      return: 5
    files:
    - name: "code01.txt"
      url: "media/workdir/code01.txt"
  - testcases:
    - statement: 'inspect("code02.txt")'
      return: 1939
    files:
    - name: "code02.txt"
      url: "media/workdir/code02.txt"
```

**Comment by pdawyndt** [comment]
With the suggestions from #116 the files could go with a single `testcase` and the multiple `testcase`s could be grouped in the same `run` (but in their separate `context`). This would be the result:
```yaml
- tab: "Inspect"
  runs:
  - separate_contexts: true
	testcases:
    - statement: 'inspect("code01.txt")'
      return: 5
      files:
      - name: "code01.txt"
        url: "media/workdir/code01.txt"
    - statement: 'inspect("code02.txt")'
      return: 1939
      files:
      - name: "code02.txt"
        url: "media/workdir/code02.txt"
```
I had no idea how to name the `separate_contexts` yet. The alternative would be to introduce `contexts` in the hierarchy.
