### ISSUE TITLE
Support language-specific literals, expressions and statements

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#399]
TESTed currently only supports language-agnostic expressions and statements to achieve the goal of programming-language agnostic test cases.

However, TESTed-DSL might also be used as a common format for specifying test suites, even for programming exercises that only target a single programming language or a limited list of programming languages. We could also support those use cases.

For exercises that target a single programming language, we could add a top-level setting `programming_language: '<language>'` to set a specific programming language. Its default value (e.g. `'abstract'`) is the current behavior: all expected return values (`return`), expressions (`expression`) and statements (`statement`) are interpreted as expressed in the abstract programming language of TESTed-DSL and translated on-the-fly into the programming language of the submission (or oracle). However, if the `programming-language` attribute is for example set to `javascript`, the test suite becomes JavaScript-specific, and all return values, expressions and statements are interpreted as expressed in JavaScript. This would obviate the need to translate the values, expression and statements in another language, and allow using language-specific syntax/constructs that are not supported in the abstract programming language of TESTed (e.g. anonymous functions).

For exercises that target a limited list of programming languages, we might provide language-specific representations for all target language at all places where the language-agnostic representation is not supported. Something like

```yaml
- cases:
  # language-specific
  - expression:
      'python': "sort_words(['SPAM', 'eggs', 'bacon'], lambda word: word.upper())"
      'javascript': 'sortWords(["SPAM", "eggs", "bacon"], word => word.toUpperCase())'
  # language-agnostic
  - return: ['bacon', 'eggs', 'SPAM']
```

This would allow mixing language-specific and language-agnostic values, expressions and statements in a single test suite. If there's a need, wherever language-specific representations are used, we could also add an `'abstract'` representation that is used for all cases where no language-specific representation is given.
