### ISSUE TITLE
Capture global scope

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#405]
TESTed could capture the global scope before and after running a test (main call, expression, statement) such that this global scope could also be evaluated by a custom oracle (the default behavior being that any global scope is accepted; no expected value can be set and no built-in oracle is needed). The global scope could be represented as a mapping of variable names (string) onto strongly typed objects. Custom oracles receive the state of the global scope before and after running the test, so the two can be compared, for example to see that no new global variables have been defined as a side-effect of running a test, that glopbal variables have not been modified, or that global variables have been created or modified).

**Comment by pdawyndt** [comment]
Think about how this could enable simple exercise like:

> The variable `x` is assigned an array `[1, 2, 3, 4]`. Add the integer `5` (`int`) to the end of this array.

So a possible test suite might look like:

```YAML
- statement: 'x = [1, 2, 3, 4]'                       # setup; storage location of list must also be captured in global scope
- <execute submisson>                             # execute submission
- expression: 'x'                                          # test script
  return: [1, 2, 3, 4, 5]
  oracle: 'custom'                                        # not only checks equality but also identity of the object
```

This requires some form of setup (code executed before the submission itself is executed). It also requires a way to explicitly put the submission at some place in the test script (by default it is automatically inserted as the first statement/expressoin in the script). This may also serve some other purposes:

- embed the submission in skeleton code (i.e. add a prefix and or suffix to the submission) provided in the test suite (e.g. student is only asked to complete a commando line: prefix is given, submission is used as a prefix; so-called fill-in-the-gaps exercise; we could also allow to modify the submission in a programmed way, as we do with test oracles)
- ???
