### ISSUE TITLE
Improve ergonomics of language-specific literals

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/universal-judge#423]
Currently, language-specific literals must be written as follows:

```yaml
- tab: "My tab"
  testcases:
  - expression:
      c: "to_string(1+1)"
      haskell: "Submission.toString (1+1)"
      runhaskell: "Submission.toString (1+1)"
      java: "Submission.toString(1+1)"
      javascript: "submission.toString(1+1)"
      kotlin: "toString(1+1)"
      python: "submission.to_string(1+1)"
      csharp: "Submission.toString(1+1)"
    return: "2"
```

This issue is to collect ideas about how to improve this situation.

- Always using a namespace is for example not possible in C, since C doesn't have namespaces. Using the same namespace everywhere is also difficult, since a TESTed "namespace" doesn't always mean the same thing: in Java this is a class name, while in Python it is a package name.
- We cannot and will not inspect these strings: these are opaque values to TESTed; we just insert them in the correct position in the generated code.
