### ISSUE TITLE
Report non-zero exit status if zero exit status is expected

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#432]
The behavior of reporting a non-zero exit status seems no long to be correct when a zero exit status is expected. This is how a non-zero exit status used to be reported ([example](https://dodona.be/nl/feedbacks/1632562560/)):

![image](https://github.com/dodona-edu/universal-judge/assets/5736113/2723dc9b-d4a0-4c12-84e6-8bfd8049e9e6)

Now the wrong exit status is no longer reported:

![image](https://github.com/dodona-edu/universal-judge/assets/5736113/e4f9e37f-9689-41b6-a79f-7493692d52dc)

I slightly changed the specification of the test suite, but the only issue that might have caused this, is that files are now specified for the individual test cases, where they used to be specified at the unit-level:

```yaml
- arguments: ["emoji.txt", "🐎", "👞"]
  stdout: "horseshoe\n"
  files:
    - name: "emoji.txt"
      url: "media/workdir/emoji.txt"
```

However, I guess this is an unrelated issue, caused by some other changes in TESTed.
