### ISSUE TITLE
Do not ignore leading & trailing whitespace by default

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/universal-judge#462]
As long as I could go back in git history, leading and trailing white space has been ignored by default. Basically, what happens when evaluating results is `expected_stdout.strip() == generated_stdout.strip()`.

Recently it was said that this should not be the default, as we want to be strict by default.

However, this would make the simple case more difficult. For example, 

```yaml
- tab: "Testen"
  testcases:
  - stdin: "Jan"
    stdout: "Hallo, Jan!"
  - stdin: "Piet"
    stdout: "Hallo, Piet!"
  - stdin: "5236-hallo!"
    stdout: "Hallo, 5236-hallo!!"
  - stdin: "'wereld'"
    stdout: "Hallo, 'wereld'!"
  - stdin: '"wereld"'
    stdout: 'Hallo, "wereld"!'
  - stdin: "    "
    stdout: "Hallo,     !"
```

would need to become:

```yaml
- tab: "Testen"
  testcases:
  - stdin: "Jan"
    stdout: "Hallo, Jan!\n"
  - stdin: "Piet"
    stdout: "Hallo, Piet!\n"
  - stdin: "5236-hallo!"
    stdout: "Hallo, 5236-hallo!!\n"
  - stdin: "'wereld'"
    stdout: "Hallo, 'wereld'!\n"
  - stdin: '"wereld"'
    stdout: 'Hallo, "wereld"!\n'
  - stdin: "    "
    stdout: "Hallo,     !\n"
```

A possible solution would be to add trailing newlines automatically to the test suite for stdout and stderr (and maybe stdin). However, we maybe also need a way to disable this behaviour then.
