### ISSUE TITLE
Testing stdin/stdout and expressions at the same time?

### ISSUE THREAD

**Issue by DieterPi** [dodona-edu/universal-judge#502]
I would like my to students to program something like this, to demonstrate the 'decomposition' of functions.

```python
def harmonic_mean( a, b ):
    value = round( 2 / ( 1 / a + 1 / b ), 2)
    return value 

# Input
a = int(input())
b = int(input())

# Using the function
c = harmonic_mean(a,b)

# Printing on screen
print(c)
```

I was thinking of using TESTed to test both stdin/stdout and the `harmonic_mean` expression. But the testing fails on the expression, I guess because when Dodona is executing the code and expecting an stdin.

I there a way to check stdin/stdout **and** expressions at the same time? Specifying to ignore stdin when testing expressions? Or should I just pass random stdin?
https://dodona.be/nl/courses/2741/series/32738/activities/185326272/

**Comment by niknetniko** [comment]
If you want to test it in the same tab, you could do something like this:

```yaml
- tab: "test function and main"
  contexts:
    - testcases:
        - stdin: |
            100
            120
          stdout: "109.09"
        - expression: "harmonisch_gemiddelde(100, 120)"
          return: 109.99
```

Separate tabs are currently a limitation of TESTed: either you need to add `if __name__ == '__main__':` (but then the main code won't be executed) or you don't (in which case the code always runs).

This is something we want to enable at some point (as it has been requested before [here](https://github.com/orgs/dodona-edu/discussions/5234)), but the specifics of Python make this difficult, so we don't have a solution yet.
