### ISSUE TITLE
Global language support

### ISSUE THREAD

**Issue by tibvdm** [dodona-edu/universal-judge#540]
The following YAML is valid and works as intended.

```YAML
- tab: geefNde
  testcases:
    - expression: 
        haskell: Submission.geefNde 2 [1, 2, 3, 4]
      return: 3
```

[The docs](https://docs.dodona.be/nl/guides/exercises/testsuites/#taalspecifieke-expressies-en-statements), however, state that I can define the language at the start of the test plan.
```YAML
- tab: "My tab"
  language: "java"
  testcases:
  - expression: "Submission.toString(1+1)"
    return: "2"
```

When I try this for the haskell language, Dodona throw an invalid DSL error
```YAML
- tab: geefNde
  language: haskell
  testcases:
    - expression: Submission.geefNde 2 [1, 2, 3, 4]
      return: 3
```
