### ISSUE TITLE
support for literal translations (map type !programming_language)

### ISSUE THREAD

**Issue by BrentBlanckaert** [dodona-edu/universal-judge#570]
This issue specifically focuses on defining how mappings in a `return` statement should be handled for different programming languages. Currently, TESTed relies on heuristics to determine whether a mapping is intended for translations or programming languages.  

A potential solution is to explicitly specify this in the `return` statement within a test suite, as illustrated below:  
```yaml
return: !programming_language
  "python": "{1, 2, 3}"
  "javascript": "new Set([1, 2, 3])"
```

**Comment by niknetniko** [comment]
To my knowledge, TESTed actually has no heuristic at the moment. I think, if a YAML map is encountered with `return`:

- If the map has `!oracle`, it is an explicit oracle.
- Else the map is considered a literal map as the return value.

I don't think there is currently support for specifying a return value in multiple languages. If added, I think an explicit tag is probably the way to go. I experimented a bit, and for example, the following:

```yaml
return:
  "python": "{1, 2, 3}"
  "javascript": "new Set([1, 2, 3])"
```

Is interpreted as a testcase where return value must be a map with the two keys `"python"` and `"javascript"`.


I do think the explicit requirement makes sense if adding other map types.

However, adding support specifically for language literals also requires adding support for actually comparing these values. This would probably involve implementing a new oracle that supports comparisons in a target programming language, similar to how the programming-language-specific oracles work (or this is how I would implement it at least).
