### ISSUE TITLE
Support default implemtations for language-specific oracles

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#579]
TESTed allows to specify programming language specific versions of expressions as statements, either consistently for a single programming language across all expressions and statements (using the `programming language` attribute)

```yaml
namespace: "Numbers"
programming_language: "java"
units:
- unit: "Numbers.oddValues"
  cases:
    - expression: "Numbers.oddValues(new int[]{1, 2, 3, 4, 5, 6, 7, 8})"
      return: [1, 3, 5, 7]
```

or for individual expressions as staments (using a YAML map with tag `!programming language`)

```yaml
namespace: "Numbers"
programming_language: "java"
units:
- unit: "Numbers.oddValues"
  cases:
    - expression: !programming_language
        java: "Numbers.oddValues(new int[]{1, 2, 3, 4, 5, 6, 7, 8})"
      return: [1, 3, 5, 7]
```

However, there is no way to work with programming-language specific version of return values. We could also look into how we could make this working:

```yaml
namespace: "Numbers"
programming_language: "java"
units:
- unit: "Numbers.oddValues"
  cases:
    - expression: 'Numbers.oddValues(new int[]{1, 2, 3, 4, 5, 6, 7, 8})'
      return: !expression "new int[]{1, 3, 5, 7}"
```

All return values by default go through TESTed, so TESTed must “understand” the what the object is, which is not the case with language-specific strings. If we don't want that, we have to use a language-specific oracle.

A possible way to avoid that language-specific oracles are always needed in this is case, is to add default comparators for language-specific types to a language module (i.e. test exact matching). These could then be superseded by custom language-specific oracles if the default behaviour is not sufficient. 

Niko wrote:

> *Another possible extension could be that if a return value has a language-specific value, that TESTed automatically turns it into a language-specific oracle in the background. But that's still future (which I also haven't really thought much about yet, so it may not be entirely possible or desirable).*
