### ISSUE TITLE
Custom check function returns invalid json?

### ISSUE THREAD

**Issue by DieterPi** [dodona-edu/universal-judge#592]
I wanted to implement a custom check function for [this exercise](https://dodona.be/nl/courses/3770/activities/1028537190/) since multiple solutions are possible. But the custom check function fails due to 'invalid json' output.

Even if I just return the following standard `EvaluationResult` object...

```python
obj = EvaluationResult(
    result = True,
    readable_actual = context.actual,
    readable_expected = context.actual
)
```

Is it because of the emoji's? Or am I missing something?

**Comment by pdawyndt** [comment]
You'll have to use Unicode escape sequences in the test specification. Here's the first two tests for [this exercise](https://dodona.be/nl/activities/1538789393/) that uses the escape sequence `\U0001F44D` for 👍 and the escape sequence `\U0001F44E` for 👎.

```yaml
units:
- unit: "IO"
  scripts:
  - stdin: "Can we start the weekend over again… I wasn't ready."
    stdout: "\U0001F44D"
  - stdin: "Today I will be as useless as the \"g\" in lasagna."
    stdout: "\U0001F44E (36 letters)"
```
